
INSERT INTO Localidades (Nombre) VALUES 
('Malvinas Argentinas'),
('Ministro Rivadavia'),
('Adrogué'),
('Burzaco'),
('Claypole'),
('Don Orione'),
('Glew'),
('José Mármol'),
('Longchamps'),
('Rafael Calzada'),
('San Francisco Solano'),
('San José'),
('Gerli'),
('Piñeyro'),
('Sarandí'),
('Villa Domínico'),
('Wilde'),
('Área Reserva Cinturón Ecológico'),
('Avellaneda'),
('Crucesita'),
('Dock Sud'),
('Bahía Blanca'),
('Grünbein'),
('Ingeniero White'),
('Villa Bordeau'),
('Villa Espora'),
('Berazategui'),
('Berazategui Oeste'),
('Carlos Tomás Sourigues'),
('El Pato'),
('Guillermo Enrique Hudson'),
('Juan María Gutiérrez'),
('Pereyra'),
('Plátanos'),
('Ranelagh'),
('Villa España'),
('Barrio Banco Provincia'),
('Barrio El Carmen Este'),
('Barrio Universitario'),
('Berisso'),
('Los Talas'),
('Villa Argüello'),
('Villa Dolores'),
('Villa Independencia'),
('Villa Nueva'),
('Villa Porteña'),
('Villa Progreso'),
('Villa San Carlos'),
('Villa Zula'),
('Punta Alta'),
('Villa del Mar'),
('Chascomús'),
('Barrio San Cayetano'),
('Dique N° 1'),
('Ensenada'),
('Isla Santiago'),
('Punta Lara'),
('Villa Catela'),
('Belén de Escobar'),
('El Cazador'),
('Garín'),
('Ingeniero Maschwitz'),
('Loma Verde'),
('Matheu'),
('Maquinista F. Savio Este'),
('Canning'),
('El Jagüel'),
('Luis Guillón'),
('Monte Grande'),
('9 de Abril'),
('El Remanso'),
('Morón'),
('Parada Robles'),
('Pavón'),
('Aeropuerto Internacional Ezeiza'),
('Canning'),
('Carlos Spegazzini'),
('José María Ezeiza'),
('La Unión'),
('Tristán Suárez'),
('Bosques'),
('Estanislao Severo Zeballos'),
('San Juan Bautista'),
('Gobernador Julio A. Costa'),
('Ingeniero Juan Allan'),
('Villa Brown'),
('Villa San Luis'),
('Villa Santa Rosa'),
('Villa Vatteone'),
('El Tropezón'),
('La Capilla'),
('Barrio Kennedy'),
('General Juan Madariaga'),
('Camet'),
('Estación Camet'),
('Mar del Plata'),
('Punta Mogotes'),
('Barrio El Casal'),
('Barrio Colinas Verdes'),
('Barrio El Coyunco'),
('Barrio Gambier'),
('Barrio La Gloria'),
('Sierra de los Padres'),
('Barrio Morabo'),
('Barrio Ruta 24 Kilómetro 10'),
('Country Club Bosque Real'),
('General Rodríguez'),
('Villa Yapeyú'),
('Barrio Parque General San Martín'),
('Billinghurst'),
('Ciudad del Libertador General San Martín'),
('Ciudad Jardín El Libertador'),
('Villa Ayacucho'),
('Villa Ballester'),
('Villa Bernardo Monteagudo'),
('Villa Chacabuco'),
('Villa Coronel José M. Zapiola'),
('Villa General Antonio J. de Sucre'),
('Villa General Eugenio Necochea'),
('Villa General José Tomás GuIdo'),
('Villa General Juan G. Las Heras'),
('Villa Godoy Cruz'),
('Villa Granaderos de San Martín'),
('Villa Gregoria Matorras'),
('Villa José León Suárez');


INSERT INTO Localidades (Nombre) VALUES 
('Villa Juan Martín de Pueyrredón'),
('Villa Libertad'),
('Villa Lynch'),
('Villa Maipú'),
('Va.María Irene de los Remedios Escalada'),
('Va.Marqués Alejandro María de Aguado'),
('Villa Parque PresIdente Figueroa Alcorta'),
('Villa Parque San Lorenzo'),
('Villa San Andrés'),
('Hurlingham'),
('Villa Santos Tesei'),
('William C. Morris'),
('Ituzaingó Centro'),
('Ituzaingó Sur'),
('Villa Gobernador Udadondo'),
('Del Viso'),
('José C. Paz'),
('Tortuguitas'),
('Aguas Verdes'),
('Lucila del Mar'),
('Mar de Ajó'),
('Mar de Ajó Norte'),
('San Bernardo'),
('Mar del Tuyú'),
('Santa Teresita'),
('Aldo Bonzi'),
('Ciudad Evita'),
('González Catán'),
('Gregorio de Laferrere'),
('IsIdro Casanova'),
('La Tablada'),
('Lomas del Mirador'),
('Rafael Castillo'),
('Ramos Mejía'),
('San Justo'),
('Tapiales'),
('20 de Junio'),
('Villa Eduardo Madero'),
('Villa Luzuriaga'),
('Virrey del Pino'),
('Gerli'),
('Lanús Este'),
('Lanús Oeste'),
('Monte Chingolo'),
('Remedios de Escalada de San Martín'),
('Valentín Alsina'),
('Abasto'),
('Ángel Etcheverry'),
('Arana'),
('Arturo Seguí'),
('Barrio El Carmen Oeste'),
('Barrio Las Malvinas'),
('Barrio Las Quintas'),
('City Bell'),
('El Retiro'),
('Joaquín Gorina'),
('José Hernández'),
('José Melchor Romero'),
('La Cumbre'),
('La Plata'),
('Lisandro Olmos'),
('Los Hornos'),
('Manuel B. Gonnet'),
('Ringuelet'),
('Rufino de Elizalde'),
('Tolosa'),
('Transradio'),
('Villa Elisa'),
('Villa Elvira'),
('Villa Garibaldi'),
('Villa Montoro'),
('Villa Parque Sicardi'),
('Banfield'),
('Llavallol'),
('Lomas de Zamora'),
('Temperley'),
('Turdera'),
('Villa Centenario'),
('Villa Fiorito'),
('Barrio Las Casuarinas'),
('Cortines'),
('Lezica y Torrezuri'),
('Luján'),
('Villa Flandria Norte'),
('Villa Flandria Sur'),
('Country Club Las Praderas'),
('Open Door'),
('Área de Promoción El Triángulo'),
('Grand Bourg'),
('Ingeniero Adolfo Sourdeaux'),
('Ingeniero Pablo Nogués'),
('Los Polvorines'),
('Malvinas Argentinas'),
('Tortuguitas'),
('Villa de Mayo'),
('La Baliza'),
('La Caleta'),
('Mar de Cobo'),
('AtlántIda'),
('Camet Norte'),
('Frente Mar'),
('Playa Dorada'),
('Santa Clara del Mar'),
('Santa Elena'),
('Barrio Lisandro de la Torre y Santa Marta'),
('Marcos Paz'),
('Libertad'),
('Mariano Acosta'),
('Merlo'),
('Pontevedra'),
('San Antonio de Padua'),
('Cuartel V'),
('Francisco Álvarez'),
('La Reja'),
('Moreno'),
('Paso del Rey'),
('Trujui'),
('Castelar'),
('El Palomar'),
('Haedo'),
('Villa Sarmiento'),
('Necochea'),
('Quequén'),
('Costa Bonita'),
('Colonia Hinojo');



INSERT INTO Localidades (Nombre) VALUES 
('Hinojo'),
('Sierras Bayas'),
('Villa Arrieta'),
('Del Viso'),
('Fátima'),
('La Lonja'),
('Los Cachorros'),
('Manzanares'),
('Manzone'),
('Maquinista F. Savio Oeste'),
('Pilar'),
('PresIdente Derqui'),
('Roberto de Vicenzo'),
('Santa Teresa'),
('Tortuguitas'),
('Villa Astolfi'),
('Villa Rosa'),
('Zelaya'),
('Cariló'),
('Ostende'),
('Pinamar'),
('Valeria del Mar'),
('Barrio América UnIda'),
('Guernica'),
('Bernal'),
('Bernal Oeste'),
('Don Bosco'),
('Ezpeleta'),
('Ezpeleta Oeste'),
('Quilmes'),
('Quilmes Oeste'),
('San Francisco Solano'),
('Villa La FlorIda'),
('Barrio Las Margaritas'),
('Rojas'),
('Villa Parque Cecir'),
('San Fernando'),
('Victoria'),
('Virreyes'),
('Acasusso'),
('Béccar'),
('Boulogne Sur Mer'),
('Martínez'),
('San IsIdro'),
('Villa Adelina'),
('Bella Vista'),
('Campo de Mayo'),
('Muñiz'),
('San Miguel'),
('La Emilia'),
('Villa Campi'),
('Villa Canto'),
('Villa Riccio'),
('Campos Salles'),
('San Nicolás de los Arroyos'),
('Alejandro Korn'),
('San Vicente'),
('Domselaar'),
('Benavídez'),
('Dique Luján'),
('Don Torcuato Este'),
('Don Torcuato Oeste'),
('El Talar'),
('General Pacheco'),
('Troncos del Talar'),
('Ricardo Rojas'),
('Rincón de Milberg'),
('Tigre'),
('Claromecó'),
('Dunamar'),
('Caseros'),
('Churruca'),
('Ciudad Jardín Lomas del Palomar'),
('Ciudadela'),
('El Libertador'),
('José Ingenieros'),
('Loma Hermosa'),
('Martín Coronado'),
('11 de Septiembre'),
('Pablo Podestá'),
('Remedios de Escalada'),
('Sáenz Peña'),
('Santos Lugares'),
('Villa Bosch'),
('Villa Raffo'),
('Carapachay'),
('FlorIda'),
('FlorIda Oeste'),
('La Lucila'),
('Munro'),
('Olivos'),
('Vicente López'),
('Villa Martelli'),
('Mar Azul'),
('Mar de las Pampas'),
('Barrio Saavedra'),
('Zárate'),
('Reta'),
('Rojas'),
('Carhué'),
('Colonia San Miguel Arcángel'),
('Delfín Huergo'),
('Espartillar'),
('Esteban Agustín Gascón'),
('La Pala'),
('Maza'),
('Rivera'),
('Villa Margarita'),
('Adolfo Gonzales Chaves'),
('De La Garma'),
('Juan E. Barra'),
('Vásquez'),
('Alberti'),
('Coronel Seguí'),
('Mechita'),
('Pla'),
('Villa Grisolía'),
('Villa María'),
('Villa Ortiz'),
('Almirante Brown'),
('Avellaneda'),
('Ayacucho'),
('La Constancia');



INSERT INTO Localidades (Nombre) VALUES 
('Solanet'),
('Udaquiola'),
('Ariel'),
('Azul'),
('Cacharí'),
('Chillar'),
('16 de Julio'),
('Bahía Blanca'),
('Cabildo'),
('General Daniel Cerri'),
('Balcarce'),
('Los Pinos'),
('Napaleofú'),
('Ramos Otero'),
('San Agustín'),
('Villa Laguna La Brava'),
('Baradero'),
('Irineo Portela'),
('Santa Coloma'),
('Villa Alsina'),
('Arrecifes'),
('Todd'),
('Viña'),
('Barker'),
('Benito Juárez'),
('López'),
('Tedín Uriburu'),
('Villa Cacique'),
('Berazategui'),
('Berisso'),
('Hale'),
('Juan F. Ibarra'),
('Paula'),
('Pirovano'),
('San Carlos de Bolívar'),
('Urdampilleta'),
('Villa Lynch Pueyrredón'),
('Bragado'),
('Comodoro Py'),
('General O Brien'),
('Irala'),
('La Limpia'),
('Juan F. Salaberry'),
('Mechita'),
('Olascoaga'),
('Warnes'),
('Altamirano'),
('Barrio Las Golondrinas'),
('Barrio Los Bosquecitos'),
('Barrio Parque Las Acacias'),
('Coronel Brandsen'),
('Gómez'),
('Jeppener'),
('OlIden'),
('Samborombón'),
('Los Cardales'),
('Barrio Los Pioneros (Barrio Tavella)'),
('Alejandro Petión'),
('Barrio El Taladro'),
('Cañuelas'),
('Gobernador Udaondo'),
('Santa Rosa'),
('Uribelarrea'),
('Vicente Casares'),
('Capitán Sarmiento'),
('La Luisa'),
('Bellocq'),
('Cadret'),
('Carlos Casares'),
('Colonia Mauricio'),
('Hortensia'),
('La Sofía'),
('Mauricio Hirsch'),
('Moctezuma'),
('Ordoqui'),
('Smith'),
('Colón'),
('Carlos Tejedor'),
('Colonia Seré'),
('Curarú'),
('Timote'),
('Tres Algarrobos'),
('Carmen de Areco'),
('Pueblo Gouin'),
('Tres Sargentos'),
('Castelli'),
('Centro Guerrero'),
('Cerro de la Gloria'),
('Villa Manuel Pomar'),
('Pearson'),
('Sarasa'),
('Villa General Arias'),
('Bajo Hondo'),
('Balneario Pehuen Co'),
('Punta Alta'),
('Aparicio'),
('Marisol'),
('Coronel Dorrego'),
('El PerdIdo'),
('Faro'),
('Irene'),
('Oriente'),
('San Román'),
('Coronel Pringles'),
('El Divisorio'),
('El Pensamiento'),
('Indio Rico'),
('Lartigau'),
('Cascada'),
('Coronel Suárez'),
('Curamalal'),
('D Orbigny'),
('Huanguelén'),
('Pasman'),
('San José'),
('Santa María'),
('Santa TrInIdad'),
('Villa La Arcadia'),
('Castilla'),
('Chacabuco'),
('Los Angeles'),
('O Higgins'),
('Rawson'),
('Chascomús');


INSERT INTO Localidades (Nombre) VALUES 
('Manuel J. Cobo'),
('Villa Parque Girado'),
('Chivilcoy'),
('Emilio Ayarza'),
('Gorostiaga'),
('La Rica'),
('Moquehuá'),
('Ramón Biaus'),
('San Sebastián'),
('Andant'),
('Arboledas'),
('Daireaux'),
('La Larga'),
('Salazar'),
('Dolores'),
('Sevigne'),
('Ensenada'),
('Escobar'),
('Esteban Echeverría'),
('Arroyo de la Cruz'),
('Parada Orlando'),
('Parada Robles - Pavón'),
('Ezeiza'),
('Florencio Varela'),
('Blaquier'),
('Florentino Ameghino'),
('Porvenir'),
('Comandante Nicanor Otamendi'),
('Mar del Sur'),
('Mechongué'),
('Miramar'),
('General Alvear'),
('Casbas'),
('Arribeños'),
('Ascensión'),
('Estación Arenales'),
('Ferré'),
('General Arenales'),
('La Angelita'),
('La Trinidad'),
('General Belgrano'),
('Gorchs'),
('General Guido'),
('Labardén'),
('General Juan Madariaga'),
('General La Madrid'),
('La Colina'),
('Las Martinetas'),
('Líbano'),
('Pontaut'),
('General Hornos'),
('General Las Heras'),
('La Choza'),
('Plomer'),
('General Lavalle'),
('Barrio Río Salado'),
('Loma Verde'),
('Ranchos'),
('Villanueva'),
('Colonia San Ricardo'),
('General Pinto'),
('Germania'),
('Villa Francia'),
('Villa Roth'),
('Barrio Santa Paula'),
('Batán'),
('Chapadmalal'),
('El Marquesado'),
('Estación Chapadmalal'),
('Mar del Plata'),
('Sierra de los Padres'),
('General Rodríguez'),
('General San Martín'),
('Baigorrita'),
('La Delfina'),
('Los Toldos'),
('San Emilio'),
('Zavalía'),
('Banderaló'),
('Cañada Seca'),
('Coronel Charlone'),
('Emilio V. Bunge'),
('General Villegas'),
('Massey'),
('Pichincha'),
('Piedritas'),
('Santa Eleodora'),
('Santa Regina'),
('Villa Saboya'),
('Villa Sauze'),
('Arroyo Venado'),
('Garré'),
('Guaminí'),
('Laguna Alsina'),
('Henderson'),
('Herrera Vegas'),
('Hurlingham'),
('Ituzaingó'),
('José C. Paz'),
('Agustín Roca'),
('Agustina'),
('Balneario Laguna de Gómez'),
('Fortín Tiburcio'),
('Junín'),
('Laplacette'),
('Saforcada'),
('Las Toninas'),
('Mar de Ajó - San Bernardo'),
('San Clemente del Tuyú'),
('Santa Teresita - Mar del Tuyú'),
('La Matanza'),
('Lanús'),
('La Plata'),
('LaprIda'),
('Pueblo Nuevo'),
('Pueblo San Jorge'),
('Coronel Boerr'),
('El Trigo'),
('Las Flores'),
('Pardo'),
('Alberdi Viejo'),
('El Dorado'),
('Fortín Acha'),
('Juan Bautista Alberdi');


INSERT INTO Localidades (Nombre) VALUES 
('Leandro N. Alem'),
('Vedia'),
('Arenaza'),
('Bayauca'),
('Bermúdez'),
('Carlos Salas'),
('Coronel Martínez de Hoz'),
('El Triunfo'),
('Las Toscas'),
('Lincoln'),
('Pasteur'),
('Roberts'),
('Triunvirato'),
('Arenas Verdes'),
('Licenciado Matienzo'),
('Lobería'),
('Pieres'),
('San Manuel'),
('Tamangueyú'),
('Antonio Carboni'),
('Elvira'),
('Laguna de Lobos'),
('Lobos'),
('Salvador María'),
('Lomas de Zamora'),
('Carlos Keen'),
('Luján'),
('Olivera'),
('Torres'),
('Atalaya'),
('General Mansilla'),
('Los Naranjos'),
('Magdalena'),
('Roberto J. Payró'),
('Vieytes'),
('Las Armas'),
('Maipú'),
('Santo Domingo'),
('Malvinas Argentinas'),
('Coronel Vidal'),
('General Pirán'),
('La Armonía'),
('Mar Chiquita'),
('Mar de Cobo'),
('Santa Clara del Mar'),
('Vivoratá'),
('Marcos Paz'),
('Gowland'),
('Mercedes'),
('Jorge Born'),
('Merlo'),
('Abbott'),
('San Miguel del Monte'),
('Zenón VIdela Dorna'),
('Balneario Sauce Grande'),
('Monte Hermoso'),
('Moreno'),
('Morón'),
('José Juan Almeyra'),
('Las Marianas'),
('Navarro'),
('Villa Moll'),
('Claraz'),
('Juan N. Fernández'),
('Necochea - Quequén'),
('Nicanor Olivera'),
('Ramón Santamarina'),
('Alfredo Demarchi'),
('Carlos María Naón'),
('12 de Octubre'),
('Dudignac'),
('La Aurora'),
('Manuel B. Gonnet'),
('Recalde'),
('Marcelino Ugarte'),
('Morea'),
('Norumbega'),
('9 de Julio'),
('Patricios'),
('Villa Fournier'),
('Colonia San Miguel'),
('Espigas'),
('Hinojo'),
('Olavarría'),
('Santa Luisa'),
('Sierra Chica'),
('Sierras Bayas'),
('Villa Alfredo Fortabat'),
('Villa La Serranía'),
('Bahía San Blas'),
('Cardenal Cagliero'),
('Carmen de Patagones'),
('José B. Casas'),
('Juan A. Pradere'),
('Stroeder'),
('Villalonga'),
('Capitán Castro'),
('San Esteban'),
('Francisco Madero'),
('Juan José Paso'),
('Magdala'),
('Mones Cazón'),
('Nueva Plata'),
('Pehuajó'),
('San Bernardo'),
('Bocayuva'),
('De Bary'),
('Pellegrini'),
('Acevedo'),
('Fontezuela'),
('Guerrico'),
('Juan A. de la Peña'),
('Juan Anchorena'),
('La Violeta'),
('Manuel Ocampo'),
('Mariano Benítez'),
('Mariano H. Alfonzo'),
('Pergamino'),
('Pinzón'),
('Rancagua'),
('Villa Angélica'),
('Villa San José'),
('Casalins'),
('Pila');


INSERT INTO Localidades (Nombre) VALUES 
('Pilar'),
('Pinamar'),
('PresIdente Perón'),
('Azopardo'),
('Bordenave'),
('Darregueira'),
('17 de Agosto'),
('Estela'),
('Felipe Solá'),
('López Lecube'),
('Puán'),
('San Germán'),
('Villa Castelar'),
('Villa Iris'),
('Alvarez Jonte'),
('Pipinas'),
('Punta Indio'),
('Verónica'),
('Quilmes'),
('El Paraíso'),
('Las Bahamas'),
('Pérez Millán'),
('Ramallo'),
('Villa General Savio'),
('Villa Ramallo'),
('Rauch'),
('América'),
('Fortín Olavarría'),
('González Moreno'),
('Mira Pampa'),
('Roosevelt'),
('San Mauricio'),
('Sansinena'),
('Sundblad'),
('La Beba'),
('Las Carabelas'),
('Los Indios'),
('Rafael Obligado'),
('Roberto Cano'),
('Sol de Mayo'),
('Villa Manuel Pomar'),
('Carlos Beguerie'),
('Roque Pérez'),
('Obligado'),
('Arroyo Corto'),
('Colonia San Martín'),
('Dufaur'),
('Espartillar'),
('Goyena'),
('Pigüé'),
('Saavedra'),
('Álvarez de Toledo'),
('Cazón'),
('Del Carril'),
('Polvaredas'),
('Arroyo Dulce'),
('Berdier'),
('Gahan'),
('Inés Indart'),
('La Invencible'),
('Salto'),
('Quenumá'),
('Salliqueló'),
('Azcuénaga'),
('Cucullú'),
('Franklin'),
('San Andrés de Giles'),
('Solís'),
('Villa Espil'),
('Villa Ruiz'),
('Duggan'),
('San Antonio de Areco'),
('Villa Lía'),
('Balneario San Cayetano'),
('Ochandío'),
('San Cayetano'),
('San Fernando'),
('San IsIdro'),
('San Miguel'),
('Conesa'),
('Erezcano'),
('General Rojo'),
('La Emilia'),
('San Nicolás de los Arroyos'),
('Villa Esperanza'),
('Gobernador Castro'),
('Pueblo Doyle'),
('Río Tala'),
('San Pedro'),
('Santa Lucía'),
('San Vicente'),
('General Rivas'),
('Suipacha'),
('De la Canal'),
('Gardey'),
('María Ignacia'),
('Tandil'),
('Crotto'),
('Tapalqué'),
('Velloso'),
('Tigre'),
('General Conesa'),
('Chasicó'),
('Tornquist'),
('Tres Picos'),
('La Gruta'),
('Villa Ventana'),
('Berutti'),
('Girodias'),
('La Carreta'),
('30 de Agosto'),
('Trenque Lauquen'),
('Trongé'),
('Balneario Orense'),
('Claromecó'),
('Copetonas'),
('Lin Calel'),
('Micaela Cascallares'),
('Orense'),
('San Francisco de Bellocq'),
('San Mayol'),
('Tres Arroyos'),
('Villa Rodríguez'),
('Tres de Febrero'),
('Ingeniero Thompson'),
('Tres Lomas'),
('Agustín Mosconi'),
('Del Valle'),
('Ernestina'),
('Gobernador Ugarte'),
('Lucas Monteverde'),
('Norberto de la Riestra'),
('Pedernales'),
('San Enrique'),
('Valdés'),
('25 de Mayo'),
('Vicente López'),
('Mar Azul'),
('Villa Gesell'),
('Argerich'),
('Hilario Ascasubi'),
('Juan Cousté'),
('Mayor Buratovich'),
('Médanos'),
('Pedro Luro'),
('Teniente Origone'),
('Escalada'),
('Lima'),
('Zárate');

